In [1]:
import numpy as np

# Creating array from list

In [4]:
arr_1d = np.array([1,2,3,4])
print("1D array:",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array:",arr_2d)

1D array: [1 2 3 4]
2D array: [[1 2 3]
 [4 5 6]]


# List vs numpy array

In [5]:
py_list = [1,2,3]
print("Python list multiplication",py_list *2)

Python list multiplication [1, 2, 3, 1, 2, 3]


In [6]:
np_array = np.array([1,2,3]) # element wise multiplication
print("Python array multiplication",np_array *2)

Python array multiplication [2 4 6]


In [7]:
import time 
start = time.time()
py_list = [i*2 for i in range(10000)]
print("\n List operation time",time.time()-start)


 List operation time 0.003998517990112305


In [8]:
start = time.time()
np_array = np.arange(10000)*2
print("\n Numpy operation time",time.time()-start)


 Numpy operation time 0.00299835205078125


## creating array from scratch

In [9]:
zeros = np.zeros((3,4))
print("zeros array:\n",zeros)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
ones = np.ones((2,3))
print("one array:\n",ones)

one array:
 [[1. 1. 1.]
 [1. 1. 1.]]
