# 📘 What is NumPy?

NumPy = Numerical Python

- The core Python library for fast numerical computing using powerful N-dimensional arrays.

- It’s written in C under the hood → much faster than Python lists for math.

- NumPy is a Python library for fast numerical computing using efficient N-dimensional arrays and vectorized mathematical operations.

# Diffference between Python List vs NumPy Array

| Python List   | NumPy Array       |
| ------------- | ----------------- |
| Slow for math | Very fast         |
| Mixed types   | Same type         |
| More memory   | Less memory       |
| No vector ops | Vector operations |



# Array Creation :

- Array Creation = Different ways to create arrays (ndarray) to store and process numerical data efficiently.

- Array Creation = Different ways to create arrays (ndarray) to store and process numerical data efficiently.

<!-- np.array([1,2,3])
np.arange(0,10,2)
np.linspace(0,1,5)
np.zeros((2,3))
np.ones((3,3))
np.empty((2,2))
np.eye(3)
np.identity(3)
np.full((2,2), 7)
 -->

# 1) Array Creation
<!-- np.array([1,2,3])
np.arange(0,10,2)
np.linspace(0,1,5)
np.zeros((2,3))
np.ones((3,3))
np.empty((2,2))
np.eye(3)
np.identity(3)
np.full((2,2), 7) -->

# 2) Random Numbers
<!-- np.random.rand(2,2)
np.random.randn(2,2)
np.random.randint(1,10,(2,3))
np.random.choice([1,2,3], 5)
np.random.seed(42) -->

# 3) Array Info / Attributes
<!-- # a.shape
# a.ndim
# a.size
# a.dtype
# a.itemsize -->

# 4) Reshape / Transform
<!-- a.reshape(2,3)
a.flatten()
a.ravel()
a.T
np.transpose(a) -->

# 5) Math Operations (Vectorized)
<!-- np.add(a, 5)
np.subtract(a, 2)
np.multiply(a, 3)
np.divide(a, 2)
np.power(a, 2)
np.sqrt(a)
np.abs(a)
np.round(a) -->

# 6) Statistics
<!-- np.sum(a)
np.mean(a)
np.median(a)
np.std(a)
np.var(a)
np.min(a)
np.max(a)
np.argmin(a)
np.argmax(a) -->

# 7) Sorting / Searching / Filtering
<!-- np.sort(a)
np.argsort(a)
np.where(a > 5)
np.unique(a)
np.count_nonzero(a) -->

# 8) Joining / Splitting
<!-- np.concatenate([a,b])
np.vstack([a,b])
np.hstack([a,b])
np.split(a, 2)
np.hsplit(a, 2)
np.vsplit(a, 2) -->

# 9) Indexing / Slicing (examples)
<!-- a[0]
a[1:4]
a[:,1]
a[a > 5] -->

# 10) Linear Algebra (np.linalg)
<!-- np.dot(a,b)
np.matmul(a,b)
np.linalg.inv(a)
np.linalg.det(a)
np.linalg.eig(a) -->

# 11) Trigonometry / Logs
<!-- np.sin(a)
np.cos(a)
np.tan(a)
np.log(a)
np.log10(a)
np.exp(a) -->


# 12) Comparison / Logic
<!-- np.equal(a,b)
np.greater(a,b)
np.less(a,b)
np.logical_and(a>1, a<5) -->

# 13) Broadcasting (auto shape match)
<!-- a + 5
a * np.array([1,2,3]) -->

# 14) Useful Utilities
<!-- np.copy(a)
np.clip(a, 0, 10)
np.repeat(a, 2)
np.tile(a, 2) -->

In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [6]:
# 2D

b = np.array([[1,2,3],[4,5,6]])


# 2) 

# Syntax:

- np.arange() → Range of values

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

# 3)    Syntax: 
- np.linspace() → 

- Equal spaced numbers

In [9]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# 4) Zeros Array:

- Syntax:np.zeros()

In [10]:
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 5) Ones Array:

- Syntax:

- np.ones()

In [11]:
np.ones((2,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 6) Identity Matrix

- np.eye()

In [12]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 7) Same value array

- Syntax:

- np.full()

In [13]:
np.full((2,3), 7)


array([[7, 7, 7],
       [7, 7, 7]])

# 8) Random Array

In [14]:
np.random.rand(3,3)      # 0 to 1
np.random.randint(1,10,(2,2))  # integers


array([[2, 3],
       [4, 6]], dtype=int32)

# 9) Empty Array

- Syntax:

- np.empty()

In [15]:
np.empty((2,2))


array([[0.25, 0.5 ],
       [0.75, 1.  ]])

# 10) Like Existing Array:

- Syntax

- np.array

In [16]:
a = np.array([[1,2],[3,4]])

np.zeros_like(a)
np.ones_like(a)


array([[1, 1],
       [1, 1]])