In [1]:
import numpy as np

In [2]:
# 1️⃣ Create array
marks = np.array([45, 67, 89, 23, 56, 90])
print("Marks:", marks)

Marks: [45 67 89 23 56 90]


In [3]:
# 2️⃣ Array properties
print("Shape:", marks.shape)
print("Dimensions:", marks.ndim)
print("Size:", marks.size)
print("Data type:", marks.dtype)

Shape: (6,)
Dimensions: 1
Size: 6
Data type: int64


In [4]:
# 3️⃣ Mathematical operations
print("Add grace marks:", marks + 5)
print("Square of marks:", marks ** 2)
print("Square root:", np.sqrt(marks))

Add grace marks: [50 72 94 28 61 95]
Square of marks: [2025 4489 7921  529 3136 8100]
Square root: [6.70820393 8.18535277 9.43398113 4.79583152 7.48331477 9.48683298]


In [5]:
# 4️⃣ Statistical functions
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Max:", np.max(marks))
print("Min:", np.min(marks))
print("Std Dev:", np.std(marks))

Total: 370
Average: 61.666666666666664
Max: 90
Min: 23
Std Dev: 23.746344747958346


In [6]:
# 5️⃣ Filtering (Boolean masking)
passed = marks[marks >= 40]
print("Passed students:", passed)

Passed students: [45 67 89 56 90]


In [7]:
# 6️⃣ Sorting
print("Sorted marks:", np.sort(marks))

Sorted marks: [23 45 56 67 89 90]


In [8]:
# 7️⃣ Unique values
print("Unique marks:", np.unique(marks))

Unique marks: [23 45 56 67 89 90]


In [9]:
# 8️⃣ Where condition
result = np.where(marks >= 40, "Pass", "Fail")
print("Result:", result)

Result: ['Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass']


In [10]:
# 9️⃣ Reshaping
matrix = marks.reshape(2, 3)
print("Reshaped matrix:\n", matrix)

Reshaped matrix:
 [[45 67 89]
 [23 56 90]]


In [11]:
# 🔟 Transpose
print("Transpose:\n", matrix.T)

Transpose:
 [[45 23]
 [67 56]
 [89 90]]


In [12]:
# 1️⃣1️⃣ Flattening
print("Flatten:", matrix.flatten())

Flatten: [45 67 89 23 56 90]


In [14]:
# 1️⃣2️⃣ Random numbers (bonus marks)
bonus = np.random.randint(1, 6, size=6)
print("Bonus marks:", bonus)

final_marks = marks + bonus
print("Final marks:", final_marks)

Bonus marks: [2 2 1 3 5 5]
Final marks: [47 69 90 26 61 95]


In [15]:

# 1️⃣3️⃣ Broadcasting
print("Increase all marks by 10:", final_marks + 10)

Increase all marks by 10: [ 57  79 100  36  71 105]


In [16]:
# 1️⃣4️⃣ Linear algebra
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("Matrix multiplication:\n", np.dot(a, b))

Matrix multiplication:
 [[19 22]
 [43 50]]


In [17]:

# 1️⃣5️⃣ Identity matrix
print("Identity matrix:\n", np.eye(3))

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
# 1️⃣6️⃣ Clipping values
print("Clipped marks (0-100):", np.clip(final_marks, 0, 100))

Clipped marks (0-100): [47 69 90 26 61 95]


# What ALL This Example Covers:

| Category       | Functions Used                     |
| -------------- | ---------------------------------- |
| Creation       | `array`, `eye`, `randint`          |
| Properties     | `shape`, `ndim`, `size`, `dtype`   |
| Math           | `+`, `**`, `sqrt`                  |
| Stats          | `sum`, `mean`, `max`, `min`, `std` |
| Filtering      | Boolean indexing                   |
| Sorting        | `sort`, `unique`                   |
| Logic          | `where`                            |
| Reshape        | `reshape`, `flatten`, `T`          |
| Random         | `random.randint`                   |
| Broadcasting   | Scalar addition                    |
| Linear Algebra | `dot`                              |
| Utility        | `clip`                             |
